---
abstract: 'implements ed(1) error handling'
author:
  - 'Jeremy Mates, <jmates@sial.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  IPC::Open3: 1.0106
  Test::More: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-EdError
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 0.01
